AWSTemplateFormatVersion: "2010-09-09"
Resources: 
  APIGatewayUsingCloudwatchRole:
    Type: "AWS::IAM::Role"
    Properties: 
      AssumeRolePolicyDocument: 
        Version: "2012-10-17"
        Statement:
          -
            Effect: "Allow"
            Principal:
              Service:
                - "apigateway.amazonaws.com"
            Action:
              - "sts:AssumeRole"
  APIGateUsingCloudwatchLogRolePolicies:
    Type: "AWS::IAM::Policy"
    Properties:
      PolicyName: "AmazonAPIGatewayPushToCloudWatchLogs"
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          -
            Effect: "Allow"
            Action:
              - "logs:CreateLogGroup"
              - "logs:CreateLogStream"
              - "logs:DescribeLogGroups"
              - "logs:DescribeLogStreams"
              - "logs:PutLogEvents"
              - "logs:GetLogEvents"
              - "logs:FilterLogEvents"
            Resource: "*"
      Roles:
          -
            Ref: "APIGatewayUsingCloudwatchRole"